# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: 'windows-2019' # 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenSetM2Home: true
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    mavenDirectory: 'D:\mavenDir'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    jdkDirectory: 'C:\Program Files\Java\jdk8u265-b01'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'test'
- script: |
    echo Starting the build
    mvn package
    java -jar target/namiAzurePipeline-1.0-SNAPSHOT-shaded.jar
    echo end the build
  displayName: 'Build with Maven'